#!/usr/bin/env node
/**
 * nexo-fabric generate
 *
 * Loads the ontology schema from a running NEXO Fabric API and generates
 * a typed TypeScript declaration file with one interface + query builder
 * per ObjectType.
 *
 * Usage:
 *   npx nexo-fabric generate --url http://localhost:8082 --token <jwt> --out ./nexo-fabric.d.ts
 *   npx nexo-fabric generate --key nxo_...   # API key auth
 */

import { writeFileSync } from 'fs'

interface PropertyDef {
  apiName: string
  dataType: 'STRING' | 'INTEGER' | 'FLOAT' | 'BOOLEAN' | 'DATETIME' | 'JSON'
  isRequired: boolean
  isPrimaryKey: boolean
}

interface LinkTypeDef {
  apiName: string
  targetObjectType: string
  cardinality: string
}

interface ObjectTypeDef {
  apiName: string
  displayName: string
  properties: PropertyDef[]
  linkTypes: LinkTypeDef[]
}

const DATA_TYPE_MAP: Record<string, string> = {
  STRING: 'string',
  INTEGER: 'number',
  FLOAT: 'number',
  BOOLEAN: 'boolean',
  DATETIME: 'string',
  JSON: 'Record<string, unknown>',
}

function tsType(dataType: string): string {
  return DATA_TYPE_MAP[dataType] ?? 'unknown'
}

async function generate(opts: { url: string; auth: string; output: string }): Promise<void> {
  console.log(`[nexo-fabric] Fetching schema from ${opts.url}...`)

  const response = await fetch(`${opts.url}/graphql`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(opts.auth.startsWith('nxo_')
        ? { 'X-API-Key': opts.auth }
        : { Authorization: `Bearer ${opts.auth}` }),
    },
    body: JSON.stringify({
      query: `{
        getAllObjectTypes {
          apiName displayName
          properties { apiName dataType isRequired isPrimaryKey }
          linkTypes { apiName targetObjectType cardinality }
        }
      }`,
    }),
  })

  if (!response.ok) {
    console.error(`[nexo-fabric] HTTP ${response.status}: ${await response.text()}`)
    process.exit(1)
  }

  const data = (await response.json()) as { data?: { getAllObjectTypes?: ObjectTypeDef[] }; errors?: unknown[] }
  if (data.errors) {
    console.error('[nexo-fabric] GraphQL errors:', JSON.stringify(data.errors, null, 2))
    process.exit(1)
  }

  const objectTypes = data.data?.getAllObjectTypes ?? []
  console.log(`[nexo-fabric] Found ${objectTypes.length} object types`)

  const lines: string[] = [
    `// AUTO-GENERATED by nexo-fabric generate`,
    `// Do not edit manually — re-run: npx nexo-fabric generate`,
    `// Generated at: ${new Date().toISOString()}`,
    ``,
    `import type { FabricClient } from '@nexoai/fabric'`,
    ``,
    `// ─── Filter Operators ──────────────────────────────────────────`,
    `export type FilterOp<T> =`,
    `  | T`,
    `  | { eq: T }`,
    `  | { neq: T }`,
    `  | { gt: T }`,
    `  | { gte: T }`,
    `  | { lt: T }`,
    `  | { lte: T }`,
    `  | { in: T[] }`,
    `  | { contains: string }`,
    ``,
  ]

  // Per-ObjectType: interface + filter type
  for (const ot of objectTypes) {
    lines.push(`// ─── ${ot.displayName} (${ot.apiName}) ──────────────`)
    lines.push(``)

    // Interface
    lines.push(`export interface ${ot.apiName} {`)
    lines.push(`  id: string`)
    for (const prop of ot.properties) {
      const optional = prop.isRequired ? '' : '?'
      lines.push(`  ${prop.apiName}${optional}: ${tsType(prop.dataType)}`)
    }
    lines.push(`}`)
    lines.push(``)

    // Filter type
    lines.push(`export type ${ot.apiName}Filter = Partial<{`)
    for (const prop of ot.properties) {
      lines.push(`  ${prop.apiName}: FilterOp<${tsType(prop.dataType)}>`)
    }
    lines.push(`}>`)
    lines.push(``)
  }

  // Typed client interface
  lines.push(`// ─── Typed Ontology Client ─────────────────────────────`)
  lines.push(``)
  lines.push(`export interface TypedOntologyClient {`)
  for (const ot of objectTypes) {
    lines.push(`  ${ot.apiName}: {`)
    lines.push(`    search(filter?: ${ot.apiName}Filter, limit?: number): Promise<{ items: ${ot.apiName}[]; total: number }>`)
    lines.push(`    get(id: string): Promise<${ot.apiName} | null>`)
    lines.push(`    create(properties: Omit<${ot.apiName}, 'id'>): Promise<${ot.apiName}>`)
    lines.push(`    ask(query: string, limit?: number): Promise<Array<{ object: ${ot.apiName}; similarity: number }>>`)

    for (const link of ot.linkTypes) {
      const methodName = link.apiName.toLowerCase().replace(/[^a-z0-9]/g, '_')
      lines.push(`    ${methodName}(objectId: string): Promise<unknown[]>`)
    }

    lines.push(`  }`)
  }
  lines.push(`}`)
  lines.push(``)
  lines.push(`declare module '@nexoai/fabric' {`)
  lines.push(`  interface FabricClient {`)
  lines.push(`    ontology: TypedOntologyClient`)
  lines.push(`  }`)
  lines.push(`}`)
  lines.push(``)

  writeFileSync(opts.output, lines.join('\n'))
  console.log(`[nexo-fabric] ✓ Generated ${opts.output} (${objectTypes.length} types, ${lines.length} lines)`)
}

// CLI parsing
function arg(name: string, fallback = ''): string {
  const i = process.argv.indexOf(`--${name}`)
  return i >= 0 ? (process.argv[i + 1] ?? fallback) : fallback
}

const url = arg('url', process.env.NEXO_API_URL ?? 'http://localhost:8082')
const token = arg('token', process.env.NEXO_TOKEN ?? '')
const apiKey = arg('key', process.env.NEXO_API_KEY ?? '')
const auth = apiKey || token
const output = arg('out', './nexo-fabric.d.ts')

if (!auth) {
  console.error('[nexo-fabric] ERROR: Missing --token or --key (or NEXO_TOKEN / NEXO_API_KEY env)')
  console.error('Usage: nexo-fabric generate --url <url> --token <jwt> [--out file.d.ts]')
  process.exit(1)
}

generate({ url, auth, output }).catch((e) => {
  console.error('[nexo-fabric] Generation failed:', e)
  process.exit(1)
})
